- name: Install and run nginx
  hosts: ansibleservers
  become: yes
  tasks: 
   - name: Installing nginx in node servers
     ansible.builtin.package:
      name: nginx
      state: present
     
   - name: run nginx
     ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes
  


