- name: variables to print
  hosts: ansibleservers
  vars: #play level, all tasks in this play have access to this vars
    COURSE: "DevOps with AWS"
    DURATION: "120Hrs"
    STUDENT: "Hemanth"
  tasks:
  - name: print the information
    ansible.builtin.debug:
    msg: "Hi, {{STUDENT}} is preparing course for {{COURSE}} and duration is {{DURATION}}"