- name: vars from files
  hosts: ansibleservers
  vars: #variabls declared from files
   vars.yml 
  tasks:
   - name: print the course info 
     ansible.builtin.debug:
      msg: "HI, {{STUDENT}} is preparing course for {{COURSE}} with {{DURATION}} and trainer is {{TRAINER}}"