- name: vars from files
  hosts: ansibleservers
  vars_files: #variabls declared from files
  - vars.yaml 
  tasks:
   - name: print the course info 
     ansible.builtin.debug:
      msg: "HI, {{STUDENT}} is preparing course for {{COURSE}} with {{DURATION}} and trainer is {{TRAINER}}"