- name: variables taking from the prompt
  hosts: ansibleservers
  vars_prompt:
  - name: COURSE
    prompt: please enter the course name
    private: false # not a confidential
  - name: TRAINER
    prompt: please enter the trainer name
    private: false # not a confidential
  - name: STUDENT
    prompt: please enter the stundent name
    private: false # not a confidential
  - name: DURATION
    prompt: please enter the duration
    private: false # not a confidential
  tasks:
  - name: print the information
    ansible.builtin.debug:
     msg: "HI, {{STUDENT}} learning {{COURSE}}, duration is {{DURATION}} and trainer is {{TRAINER}}"

