- name: variables to print
  hosts: ansibleservers
  tasks:
  - name: print the information
    ansible.builtin.debug:
      msg: "Hello {{NAME}}, good {{GREETING}}"

      ##ansible-playbook -i inventory.ini -e ansible_username=ec2-user -e ansible_password=DevOps321 09-vars-from-args.yaml -e "NAME=Ramesh GREETING=Morning"