- name: create user
  hosts: ansibleservers
  become: yes
  tasks:
  - name: check user exist or not
    ansible.builtin.command: id expense
    register: USER #here USER is a variable that stores output from above command "id expense"
    ignore_errors: True

  - name: print the user information
    ansible.builtin.debug:
      msg: "user info: {{ USER }}"

  - name: create user
    ansible.builtin.command: useradd expense
    when: USER.rc != 0