- name: loops demo
  hosts: local
  connection: local
  become: yes
  tasks:
   - name: install packages
     ansible.builtin.package:
      name: " {{ item }}"  #item is the reserved keyword in ansible
      state: present
     loop:
     - nginx
     - ansible
     - httpd
     - mysql