- name: using loops adding and removing packages in server
  hosts: local
  connection: localhost
  become: yes
  tasks:
  - name: install packages
    ansible.builtin.package:
     name: "{{item.name}}"
     state: "{{item.state}}"

  loop:
  - {name: nginx , state: present}
  - {name: httpd , state: absent}
  - {name: nginx , state: present}
  - {name: mysql , state: absent}
  