- name: demo on filters/functions
  hosts: ansibleservers
  tasks: 
  - name: print default variables
    ansible.builtin.debug:
     msg: "Hello {{course | default('Ansible')}}" #here course variable has not defind so in ansible by using default filter we can achieve varibales
  
  - name: print in uppercase
    vars:
      greetings: "hello ramesh"
    ansible.builtin.debug:
      msg: "My name is {{greetings | upper}}"

  - name: print in lowercase
    vars:
      greetings: "HELLO RAMESH"
    ansible.builtin.debug:
      msg: "My name is {{greetings | lower}}"
  #using filters to manipulte data-->google it
  - name: print unique values
    vars:
      numbers: [1,2,3,45,643,4,643,53,5,7,7,5,7]
    ansible.builtin.debug:
      msg: "unique values of a numbers:{{numbers | unique}}"

  - name: print minimum and maximum numbers
    vars:
      numbers: [1,2,3,45,643,4,643,53,5,7,7,5,7]
    ansible.builtin.debug:
      msg: "Min: {{numbers|min}}, Max: {{numbers| max}}"

