- name: demo on filters/functions
  hosts: ansibleservers
  tasks: 
  - name: print default variables
    ansible.builtin.debug:
     msg: "Hello {{course | default('Ansible')}}" #here course variable has not defind so in ansible by using default filter we can achieve varibales
  
  - name: print in uppercase
    vars:
      greetings: "hello ramesh"
    ansible.builtin.debug:
      msg: "My name is {{greetings | upper}}"

  - name: print in lowercase
    vars:
      greetings: "HELLO RAMESH"
    ansible.builtin.debug:
      msg: "My name is {{greetigs | lower}}"

