- name: diffrence bte command and shell
  hosts: local
  connection: local
  tasks:
  - name: to execute by using command
    #ansible.builtin.command: ls -lrt > /tmp/output.txt 
    #command module, just executes the command
    ansible.builtin.shell: ls -lrt > /tmp/output.txt 
    #shell module, login to the server and execute command