- name: creating ec2_instance
  hosts: local
  connection: local
  vars:
    subnet_id: subnet-0755a33f9c8388b31
    sg: sg-04de82942b1f8408d
    ami_id: ami-09c813fb71547fc4f    # this chanes have modify
    instances:
    - mysql
    - backend
    - frontend
    zone: HemanthKumarsankar
  tasks: 
  - name: creating ec2_servser in aws
    amazon.aws.ec2_instance:
      name: "{{item}}"
      vpc_subnet_id: "{{subnet_id}}"
      instance_type: "t3.micro"
      security_group: "{{sg}}"
      image_id: "{{ami_id}}"
    loop: "{{instances}}"
    register: ec2_instances

    ####installed boto3 & botocore library
    # pipe3.9 install boto3 botocore
    #The error was: botocore.exceptions.NoCredentialsError: Unable to locate credentials
     # configured CLI for anuthentication
    #IAM->users->create user->Attach policies directly->AdministratorAccess-(job functio)->create user->sercurity cerdinals->create access key->CLI->create
        # aws configure
    
  - name: print the output
    ansible.builtin.debug:
      msg: "{{ec2_instances}}"

#ec2_instances.results -->list type
#google- anisble r53
  - name: create r53 records
    amazon.aws.route53:
      state: present
      zone: "{{zone}}"
      record: "{{}}" #mysql
      type: A
      ttl: 1
      value: "{{ item.instance[0].private-ip_address}}"
    #In loop here results called as item from that intances we get into listinstance[0] we required private ips so we can give as .private-ip_address
      wait: true
      

    loop: "{{ec2_instances.resluts}}"
     