- name: creating ec2_instance
  hosts: local
  connection: local
  vars:
    subnet_id: subnet-0755a33f9c8388b31
    sg: sg-04de82942b1f8408d
    ami_id: ami-09c813fb71547fc4f    # this chanes have modify
    instnaces:
    - mysql
    - backend
    - frontend
  tasks: 
  - name: creating ec2_servser in aws
    amazon.aws.ec2_instance:
      name: "{{item}}"
      vpc_subnet_id: "{{subnet_id}"
      instance_type: "t3.micro"
      security_group: "{{sg}}"
      image_id: "{{ami_id}}"
  loop: "{{instances}}"
  register: ec2_instances

     